// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface PCRoomStatus {
    "name": string;
    "maxSeats": string;
    "currentSeats": string;
    "availableUntil": string;
}

/**
 * Campusmate
 */
export interface ScheduleEntry {
    "className": string;
    "code": string;
    "room": string;
    "instructor": string;
    "weekday": number;
    "period": number;
}
