// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface LoginParam {
    "userId": string;
    "password": string;
}

/**
 * Campusmate
 */
export interface ScheduleEntry {
    "className": string;
    "code": string;
    "room": string;
    "instructor": string;
    "weekday": number;
    "period": number;
}
