// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

export function GetApp(): $CancellablePromise<application$0.App | null> {
    return $Call.ByID(3108208891);
}

export function GetOpenAMPassword(): $CancellablePromise<string> {
    return $Call.ByID(635336207);
}

export function GetOpenAMToken(): $CancellablePromise<string> {
    return $Call.ByID(3990794231);
}

export function GetOpenAMTokenExpireTime(): $CancellablePromise<number> {
    return $Call.ByID(2446327273);
}

/**
 * getters and setters for the state fields
 */
export function GetOpenAMUserId(): $CancellablePromise<string> {
    return $Call.ByID(3096996224);
}

export function IsAppInitialized(): $CancellablePromise<boolean> {
    return $Call.ByID(653389443);
}

export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(3151285663, app);
}

export function SetAppInitialized(initialized: boolean): $CancellablePromise<void> {
    return $Call.ByID(2045650051, initialized);
}

export function SetOpenAMPassword(password: string): $CancellablePromise<void> {
    return $Call.ByID(1172970595, password);
}

export function SetOpenAMToken(token: string): $CancellablePromise<void> {
    return $Call.ByID(3914778283, token);
}

export function SetOpenAMTokenExpireTime(expireTime: number): $CancellablePromise<void> {
    return $Call.ByID(2528793093, expireTime);
}

export function SetOpenAMUserId(userId: string): $CancellablePromise<void> {
    return $Call.ByID(20607460, userId);
}
