// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Widget {
    "widgetId": string;
    "accentColor": string;
    "charColor": string;
    "position": number;
}
