// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetBestTextColorForAccent(accentColor: string): $CancellablePromise<string> {
    return $Call.ByID(261263735, accentColor);
}

export function GetWidgetById(widgetId: string): $CancellablePromise<$models.Widget | null> {
    return $Call.ByID(4052954402, widgetId);
}

export function GetWidgets(): $CancellablePromise<$models.Widget[] | null> {
    return $Call.ByID(1711047311);
}

export function IsPrinterEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(2213219971);
}

export function LoadSettingFromStorage(): $CancellablePromise<void> {
    return $Call.ByID(3845204619);
}

export function RemoveWidget(widgetId: string): $CancellablePromise<void> {
    return $Call.ByID(1888065110, widgetId);
}

export function SaveSettingToStorage(): $CancellablePromise<void> {
    return $Call.ByID(3841495409);
}

export function SetPrinterEnabled(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(13076279, enabled);
}

export function SetWidget(widget: $models.Widget): $CancellablePromise<void> {
    return $Call.ByID(1501450298, widget);
}

export function SetWidgets(widgets: $models.Widget[] | null): $CancellablePromise<void> {
    return $Call.ByID(718824171, widgets);
}
